#!/usr/bin/env node

/**
 * Setup script for Alliance Demo
 * Helps configure environment variables for new machines
 */

const fs = require("fs");
const path = require("path");
const os = require("os");

console.log("🚀 Alliance Demo Setup");
console.log("=====================\n");

// Get the machine's IP address
function getLocalIP() {
	const interfaces = os.networkInterfaces();
	for (const devName in interfaces) {
		const iface = interfaces[devName];
		for (let i = 0; i < iface.length; i++) {
			const alias = iface[i];
			if (
				alias.family === "IPv4" &&
				alias.address !== "127.0.0.1" &&
				!alias.internal
			) {
				return alias.address;
			}
		}
	}
	return "192.168.1.100"; // fallback
}

const localIP = getLocalIP();
console.log(`📡 Detected local IP: ${localIP}`);

// Create server .env file
const serverEnvPath = path.join(__dirname, "server", ".env");
const serverEnvContent = `# Server Environment Configuration
# Generated by setup script on ${new Date().toISOString()}

# Server Configuration
PORT=5000

# Network Configuration - Your machine's IP address
HOST_IP=${localIP}

# MongoDB Configuration (Optional - app runs in offline mode if unavailable)
MONGODB_URI=mongodb+srv://rjbulcher:BkfvbQmMeu2KGC3f@main.lurvagf.mongodb.net/alliance-demo?retryWrites=true&w=majority&appName=main

# Environment
NODE_ENV=development
`;

// Create client .env file
const clientEnvPath = path.join(__dirname, "client", ".env");
const clientEnvContent = `# Client Environment Configuration
# Generated by setup script on ${new Date().toISOString()}

# Server Connection - Your machine's IP address
REACT_APP_SERVER_HOST_IP=${localIP}
REACT_APP_SERVER_PORT=5000

# Built server URL
REACT_APP_SERVER_URL=http://${localIP}:5000

# React App Configuration
REACT_APP_ENVIRONMENT=development
`;

try {
	// Write server .env
	fs.writeFileSync(serverEnvPath, serverEnvContent);
	console.log("✅ Created server/.env");

	// Write client .env
	fs.writeFileSync(clientEnvPath, clientEnvContent);
	console.log("✅ Created client/.env");

	console.log("\n🎯 Setup Complete!");
	console.log("\nNext steps:");
	console.log("1. Run: npm run install-all");
	console.log("2. Run: npm run dev");
	console.log("\n📱 Your demo URLs will be:");
	console.log(`   Display: http://${localIP}:5000/display`);
	console.log(`   Controller: http://${localIP}:5000/controller`);
	console.log(`   Admin: http://${localIP}:5000/admin`);
	console.log(
		"\n💡 To use on a different machine, run this setup script again or manually update the .env files."
	);
} catch (error) {
	console.error("❌ Error creating environment files:", error.message);
	process.exit(1);
}
